name: Go Project CI - Server
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.24.x"

            - name: Client Directory
              run: cd ./client
            - name: Install Client Dependencies
              run: go get .
            - name: Build Client
              run: go build
            - name: Test Client
              run: go test

