name: Go Project CI - Server
on:
    push:
        paths:
            - "server/**"
            - "models/**"
            - ".github/workflows/server.yml"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.24.x"

            - name: Install Dependencies
              run: go get .
            - name: Server Directory
              run: cd ./server
            - name: Build Server
              run: go build
            - name: Test Server
              run: go test

